### ISSUE TITLE
joblib import error

### ISSUE THREAD

**Issue by bnovik0v** [PIA-Group/BioSPPy#76] opened 2021-03-25 14:16 UTC
i tried to import the **storage** module from the package and error occurred.

code:
`from biosppy import storage`

error:
`cannot import name 'joblib' from 'sklearn.externals`

I use biosppy 0.6.1

**Comment by afonsocraposo** [comment] 2021-05-28 13:38
Could not reproduce this error. Doing:
```python
from biosppy import storage
```
Raised no errors. Closing this issue. Feel free to reopen.

**Closed as completed by afonsocraposo** 2021-05-28 13:38 UTC
